uuu: fix build on openSUSE tumbleweed
Met error on openSUSE tumbleweed:
[ 93%] Linking CXX executable uuu
/usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld:
../libuuu/libuuc_s.a(zip.cpp.o): undefined reference to symbol 'inflateEnd'
/lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [uuu/CMakeFiles/uuu.dir/build.make:100: uuu/uuu] Error 1
make[1]: *** [CMakeFiles/Makefile2:180: uuu/CMakeFiles/uuu.dir/all] Error 2

Need to add libz.

Signed-off-by: Peng Fan <peng.fan@nxp.com>