include missing stdint.h
This fixes build latest gcc-14

Fixes build errors below

/mnt/b/yoe/master/build/tmp/work/x86_64-nativesdk-yoesdk-linux/nativesdk-uuu/1.5.21/git/libuuu/libcomm.h:106:8: error: 'uint16_t' does not name a type
  106 | inline uint16_t EndianSwap(uint16_t x)
      |        ^~~~~~~~
/mnt/b/yoe/master/build/tmp/work/x86_64-nativesdk-yoesdk-linux/nativesdk-uuu/1.5.21/git/libuuu/libcomm.h:106:8: note: 'uint16_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'

Signed-off-by: Khem Raj <raj.khem@gmail.com>